/**
 * Generates JSON and Markdown export of the discovered course structure.
 * Both formats are downloaded to the user's machine via chrome.downloads (data URLs).
 */

import type { CourseData, Resource } from '../shared/types';

// ─── JSON export ───────────────────────────────────────────────────────────

export function buildJsonExport(course: CourseData): string {
  return JSON.stringify(course, null, 2);
}

// ─── Markdown export ───────────────────────────────────────────────────────

export function buildMarkdownExport(course: CourseData): string {
  const lines: string[] = [];

  lines.push(`# ${course.title}`);
  lines.push('');
  lines.push(`- **URL:** ${course.url}`);
  lines.push(`- **Domain:** ${course.domain}`);
  lines.push(`- **Scanned at:** ${course.scannedAt}`);
  if (course.completedAt) lines.push(`- **Scan completed:** ${course.completedAt}`);
  lines.push('');

  // Summary stats
  const totalLessons = course.modules.reduce((s, m) => s + m.lessons.length, 0);
  const totalResources = course.modules.reduce(
    (s, m) => s + m.lessons.reduce((ls, l) => ls + l.resources.length, 0),
    0,
  );
  lines.push(`**${course.modules.length} modules · ${totalLessons} lessons · ${totalResources} resources**`);
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const mod of course.modules) {
    lines.push(`## ${padNum(mod.index + 1, course.modules.length)} – ${mod.title}`);
    lines.push('');

    if (mod.lessons.length === 0) {
      lines.push('_No lessons discovered._');
      lines.push('');
      continue;
    }

    for (const lesson of mod.lessons) {
      lines.push(
        `### ${padNum(lesson.index + 1, mod.lessons.length)} – [${lesson.title}](${lesson.url})`,
      );
      lines.push('');

      if (!lesson.visited) {
        lines.push('> ⚠️ This lesson was not visited during the scan.');
        lines.push('');
        continue;
      }

      if (lesson.resources.length === 0) {
        lines.push('_No downloadable resources found._');
        lines.push('');
        continue;
      }

      lines.push('| File | Type | Status | Path |');
      lines.push('|------|------|--------|------|');

      for (const res of lesson.resources) {
        const link = `[${res.filename}](${res.url})`;
        const type = res.type.toUpperCase();
        const status = statusEmoji(res.status) + ' ' + res.status.replace(/_/g, ' ');
        const path = res.downloadPath ? `\`${res.downloadPath}\`` : '–';
        lines.push(`| ${link} | ${type} | ${status} | ${path} |`);
      }

      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('> *Generated by Course Library Exporter. This extension only downloads explicitly provided files.*');
  lines.push('> *It does not bypass DRM, paywalls, or any access controls.*');

  return lines.join('\n');
}

// ─── Download helpers ──────────────────────────────────────────────────────

/** Trigger a browser download for a text string */
export function downloadText(filename: string, content: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);

  chrome.downloads.download(
    { url, filename, saveAs: false, conflictAction: 'uniquify' },
    () => {
      // Revoke after a delay to allow the download to start
      setTimeout(() => URL.revokeObjectURL(url), 5_000);
    },
  );
}

export function exportCourse(course: CourseData): void {
  const safeTitle = course.title.replace(/[/\\:*?"<>|]/g, '-').slice(0, 60);
  const datestamp = new Date().toISOString().slice(0, 10);

  downloadText(
    `Course Library Exporter/${safeTitle}/${safeTitle}-${datestamp}.json`,
    buildJsonExport(course),
    'application/json',
  );

  downloadText(
    `Course Library Exporter/${safeTitle}/${safeTitle}-${datestamp}.md`,
    buildMarkdownExport(course),
    'text/markdown',
  );
}

// ─── Utility ───────────────────────────────────────────────────────────────

function padNum(n: number, total: number): string {
  const digits = String(total).length;
  return String(n).padStart(digits, '0');
}

function statusEmoji(status: Resource['status']): string {
  switch (status) {
    case 'download_complete': return '✅';
    case 'download_started': return '⬇️';
    case 'download_failed': return '❌';
    case 'skipped_streaming': return '⏭️';
    case 'downloadable_allowed': return '🔗';
    default: return '🔍';
  }
}
